export default {
  project: {
    slug: "cafe-sonnenblume",
    name: "Café Sonnenblume",
    language: "de-DE",
  },
  brand: {
    name: "Café Sonnenblume",
    tagline: "Warm. Freundlich. Hausgemacht.",
    logoText: "Café Sonnenblume",
    colors: {
      sunflower: "#F6C453",
      earth: "#6B4F2A",
      leaf: "#2E5E2A",
      cream: "#FFF7E6",
      accent: "#FF9F1C",
      ink: "#2B2B2B",
      muted: "#8A8A8A",
    },
  },
  i18n: {
    defaultLocale: "de-DE",
    currency: "EUR",
    currencyDisplay: {
      symbol: "€",
      position: "post",
      decimalSeparator: ",",
      thousandSeparator: ".",
      precision: 2,
    },
    timezone: "Europe/Berlin",
    dateFormat: "DD.MM.YYYY",
    timeFormat: "HH:mm",
  },
  theme: {
    fonts: {
      heading: { family: "Merriweather", weights: [400, 700] },
      body: { family: "Quicksand", weights: [400, 600] },
    },
    radius: { sm: 6, md: 10, lg: 16, xl: 24 },
    shadows: {
      sm: "0 1px 3px rgba(0,0,0,0.08)",
      md: "0 6px 18px rgba(0,0,0,0.12)",
      lg: "0 14px 30px rgba(0,0,0,0.18)",
    },
    layout: { maxWidth: 1200, gutter: 24, sectionSpacing: 72 },
    buttons: {
      primary: { bg: "#F6C453", text: "#2B2B2B", hoverBg: "#E5B443" },
      secondary: { bg: "#2E5E2A", text: "#FFF7E6", hoverBg: "#274F23" },
      ghost: { bg: "transparent", text: "#2B2B2B", hoverBg: "rgba(0,0,0,0.06)" },
    },
  },
  seo: {
    defaultTitle: "Café Sonnenblume | Berlin Prenzlauer Berg",
    titleTemplate: "%s · Café Sonnenblume",
    description:
      "Warme, freundliche Nachbarschaftscafé in Berlin-Prenzlauer Berg: hausgemachte Kuchen, Frühstück, Spezialitätenkaffee und Limonaden. Täglich geöffnet – wir freuen uns auf Ihren Besuch!",
    keywords: [
      "Café Berlin",
      "Prenzlauer Berg",
      "Frühstück",
      "Kaffee",
      "Kuchen",
      "Limonade",
      "Gemütlich",
    ],
    locale: "de_DE",
    canonical: "/",
    openGraph: {
      type: "website",
      siteName: "Café Sonnenblume",
      title: "Café Sonnenblume | Berlin Prenzlauer Berg",
      description:
        "Hausgemachte Kuchen, fair gehandelter Kaffee und eine freundliche Atmosphäre – mitten in Prenzlauer Berg.",
      images: [],
    },
    twitter: {
      card: "summary_large_image",
      creator: "@",
      site: "@",
      title: "Café Sonnenblume",
      description: "Warme, freundliche Café-Kultur in Berlin.",
    },
    sitemap: { enabled: true, changefreq: "weekly", priority: 0.7 },
  },
  navigation: {
    primary: [
      { label: "Start", href: "#start", sectionId: "hero" },
      { label: "Speisekarte", href: "#speisekarte", sectionId: "menu" },
      { label: "Öffnungszeiten", href: "#oeffnungszeiten", sectionId: "hours" },
      { label: "Kontakt", href: "#kontakt", sectionId: "contact" },
    ],
    cta: { label: "Anfrage senden", href: "#kontakt", style: "primary" },
  },
  footer: {
    columns: [
      {
        title: "Café Sonnenblume",
        items: [
          { label: "Sonnenblumenweg 12", href: null },
          { label: "10437 Berlin (Prenzlauer Berg)", href: null },
          { label: "Tel. +49 30 12345678", href: "tel:+493012345678" },
          { label: "hallo@cafe-sonnenblume.de", href: "mailto:hallo@cafe-sonnenblume.de" },
        ],
      },
      {
        title: "Öffnungszeiten",
        items: [
          { label: "Mo–Fr: 08:00–18:00", href: "#oeffnungszeiten" },
          { label: "Sa–So: 09:00–16:00", href: "#oeffnungszeiten" },
        ],
      },
      {
        title: "Folgen",
        items: [
          { label: "Instagram", href: "https://instagram.com/cafe.sonnenblume" },
        ],
      },
    ],
    note: "Alle Preise in Euro. Änderungen vorbehalten.",
  },
  data: {
    hours: {
      timezone: "Europe/Berlin",
      regular: {
        monday: { open: "08:00", close: "18:00" },
        tuesday: { open: "08:00", close: "18:00" },
        wednesday: { open: "08:00", close: "18:00" },
        thursday: { open: "08:00", close: "18:00" },
        friday: { open: "08:00", close: "18:00" },
        saturday: { open: "09:00", close: "16:00" },
        sunday: { open: "09:00", close: "16:00" },
      },
      kitchen: {
        breakfast: { start: "08:00", end: "12:00" },
        bakery: { start: "08:00", end: "18:00" },
      },
      exceptions: [],
      notes: "Feiertage können abweichen.",
    },
    contact: {
      address: {
        street: "Sonnenblumenweg 12",
        postalCode: "10437",
        city: "Berlin",
        district: "Prenzlauer Berg",
        country: "DE",
        full: "Sonnenblumenweg 12, 10437 Berlin",
      },
      coordinates: { lat: 52.5412, lng: 13.4125 },
      phone: "+49 30 12345678",
      email: "hallo@cafe-sonnenblume.de",
      directions:
        "U2 Eberswalder Straße, 6 Minuten zu Fuß. Straßenbahn M1/M10 bis Eberswalder Straße.",
      social: [
        {
          platform: "instagram",
          label: "@cafe.sonnenblume",
          url: "https://instagram.com/cafe.sonnenblume",
        },
      ],
      form: {
        id: "contactForm",
        title: "Schreiben Sie uns",
        intro:
          "Fragen, Vorbestellungen oder Feedback? Wir melden uns so schnell wie möglich.",
        method: "POST",
        action: "/api/contact",
        encoding: "application/json",
        honeypotFieldName: "website",
        minSubmitTimeSeconds: 3,
        successMessage:
          "Vielen Dank! Ihre Nachricht wurde erfolgreich gesendet.",
        errorMessage:
          "Entschuldigung, etwas ist schiefgelaufen. Bitte versuchen Sie es später erneut.",
        fields: [
          {
            type: "text",
            name: "vorname",
            label: "Vorname",
            placeholder: "Vorname",
            required: true,
            maxLength: 80,
          },
          {
            type: "text",
            name: "nachname",
            label: "Nachname",
            placeholder: "Nachname",
            required: false,
            maxLength: 80,
          },
          {
            type: "email",
            name: "email",
            label: "E-Mail",
            placeholder: "name@example.com",
            required: true,
            validation: {
              pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
              message: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
            },
          },
          {
            type: "tel",
            name: "telefon",
            label: "Telefon (optional)",
            placeholder: "+49 ...",
            required: false,
            validation: {
              pattern: "^[0-9+()\\s-]{6,}$",
              message: "Bitte geben Sie eine gültige Telefonnummer ein.",
            },
          },
          {
            type: "select",
            name: "betreff",
            label: "Betreff",
            required: true,
            options: [
              { label: "Allgemeine Anfrage", value: "allgemein" },
              { label: "Vorbestellung", value: "vorbestellung" },
              { label: "Feedback", value: "feedback" },
              { label: "Catering", value: "catering" },
            ],
          },
          {
            type: "textarea",
            name: "nachricht",
            label: "Nachricht",
            placeholder: "Ihre Nachricht...",
            required: true,
            minLength: 10,
            maxLength: 2000,
          },
          {
            type: "checkbox",
            name: "einwilligung",
            label:
              "Ich stimme der Verarbeitung meiner Angaben zum Zweck der Bearbeitung meiner Anfrage zu.",
            required: true,
          },
        ],
      },
    },
    menu: {
      currency: "EUR",
      categories: [
        {
          id: "heissgetraenke",
          title: "Heißgetränke",
          items: [
            {
              id: "espresso",
              name: "Espresso",
              description: "Kräftig und aromatisch, Single Shot",
              price: { amount: 2.2, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [],
            },
            {
              id: "doppio",
              name: "Espresso Doppio",
              description: "Doppelte Portion Espresso",
              price: { amount: 3.2, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [],
            },
            {
              id: "filterkaffee",
              name: "Filterkaffee",
              description: "Schonend gefiltert, fair gehandelte Bohnen",
              price: { amount: 2.5, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [
                { label: "Hafermilch", priceDelta: 0.4 },
                { label: "Mandelmilch", priceDelta: 0.5 },
              ],
            },
            {
              id: "cappuccino",
              name: "Cappuccino",
              description: "Mit cremigem Milchschaum",
              price: { amount: 3.2, currency: "EUR" },
              allergens: ["MILK"],
              tags: ["vegetarisch"],
              options: [
                { label: "Hafermilch", priceDelta: 0.4 },
                { label: "Laktosefrei", priceDelta: 0.3 },
              ],
            },
            {
              id: "latte",
              name: "Latte Macchiato",
              description: "Milder Kaffee mit viel Milch",
              price: { amount: 3.8, currency: "EUR" },
              allergens: ["MILK"],
              tags: ["vegetarisch"],
              options: [
                { label: "Hafermilch", priceDelta: 0.4 },
                { label: "Sirup (Vanille/Haselnuss)", priceDelta: 0.5 },
              ],
            },
            {
              id: "schokolade",
              name: "Heiße Schokolade",
              description: "Hausgemacht, mit echter Schokolade",
              price: { amount: 3.4, currency: "EUR" },
              allergens: ["MILK"],
              tags: ["vegetarisch"],
              options: [],
            },
            {
              id: "tee",
              name: "Tee",
              description: "Minze, Kräuter oder Schwarztee",
              price: { amount: 2.8, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [],
            },
          ],
        },
        {
          id: "kalte-getraenke",
          title: "Kalte Getränke",
          items: [
            {
              id: "limonade",
              name: "Hausgemachte Limonade Zitrone-Ingwer",
              description: "Frisch, spritzig, leicht scharf",
              price: { amount: 3.5, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [],
            },
            {
              id: "eiskaffee",
              name: "Eiskaffee",
              description: "Kaffee auf Eis mit Milch",
              price: { amount: 4.2, currency: "EUR" },
              allergens: ["MILK"],
              tags: ["vegetarisch"],
              options: [{ label: "Hafermilch", priceDelta: 0.4 }],
            },
            {
              id: "apfelschorle",
              name: "Apfelschorle (0,33 l)",
              description: "Erfrischend und fruchtig",
              price: { amount: 2.8, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [],
            },
            {
              id: "rhabarberschorle",
              name: "Rhabarberschorle (0,33 l)",
              description: "Süß-sauer, perfekt gekühlt",
              price: { amount: 2.9, currency: "EUR" },
              allergens: [],
              tags: ["vegan"],
              options: [],
            },
          ],
        },
        {
          id: "fruehstueck",
          title: "Frühstück",
          items: [
            {
              id: "sonnenblumen-teller",
              name: "Sonnenblumen-Frühstücksteller",
              description:
                "Bauernbrot, Käse, Tomate, Gurke, Butter & Marmelade",
              price: { amount: 8.9, currency: "EUR" },
              allergens: ["GLUTEN", "MILK"],
              tags: ["vegetarisch"],
              options: [{ label: "Zusätzliche Avocado", priceDelta: 1.5 }],
            },
            {
              id: "porridge",
              name: "Veganes Porridge",
              description: "Hafer, Beeren, geröstete Nüsse",
              price: { amount: 6.9, currency: "EUR" },
              allergens: ["NUTS"],
              tags: ["vegan"],
              options: [{ label: "Ahornsirup", priceDelta: 0.3 }],
            },
            {
              id: "avocado-brot",
              name: "Avocado-Brot",
              description: "Sauerteig, Avocado, Chiliflocken, Zitrone",
              price: { amount: 7.5, currency: "EUR" },
              allergens: ["GLUTEN"],
              tags: ["vegan"],
              options: [{ label: "Pochiertes Ei", priceDelta: 1.2 }],
            },
            {
              id: "ruehrei",
              name: "Rührei",
              description: "Mit Schnittlauch und Brot",
              price: { amount: 6.5, currency: "EUR" },
              allergens: ["EGG", "GLUTEN"],
              tags: ["vegetarisch"],
              options: [],
            },
            {
              id: "joghurt-granola",
              name: "Joghurt mit Granola",
              description: "Knuspriges Granola, Honig",
              price: { amount: 5.9, currency: "EUR" },
              allergens: ["MILK", "NUTS", "GLUTEN"],
              tags: ["vegetarisch"],
              options: [],
            },
          ],
        },
        {
          id: "gebaeck",
          title: "Gebäck",
          items: [
            {
              id: "zimtschnecke",
              name: "Zimtschnecke",
              description: "Frisch gebacken, mit Zuckerguss",
              price: { amount: 3.0, currency: "EUR" },
              allergens: ["GLUTEN", "MILK"],
              tags: ["vegetarisch"],
              options: [],
            },
            {
              id: "karottenkuchen",
              name: "Karottenkuchen",
              description: "Saftig, mit Frischkäse-Frosting",
              price: { amount: 3.5, currency: "EUR" },
              allergens: ["GLUTEN", "EGG", "NUTS", "MILK"],
              tags: ["vegetarisch"],
              options: [],
            },
            {
              id: "blaubeer-muffin",
              name: "Blaubeer-Muffin",
              description: "Locker und fruchtig",
              price: { amount: 2.8, currency: "EUR" },
              allergens: ["GLUTEN", "EGG", "MILK"],
              tags: ["vegetarisch"],
              options: [],
            },
            {
              id: "croissant",
              name: "Croissant",
              description: "Butterig und knusprig",
              price: { amount: 2.2, currency: "EUR" },
              allergens: ["GLUTEN", "MILK", "EGG"],
              tags: ["vegetarisch"],
              options: [],
            },
            {
              id: "gf-schokokuchen",
              name: "Glutenfreier Schokokuchen",
              description: "Intensiv schokoladig",
              price: { amount: 3.6, currency: "EUR" },
              allergens: ["EGG", "NUTS"],
              tags: ["glutenfrei"],
              options: [],
            },
          ],
        },
        {
          id: "saisonal",
          title: "Saisonale Spezialitäten",
          items: [
            {
              id: "erdbeer-rhabarber-tarte",
              name: "Erdbeer-Rhabarber-Tarte",
              description: "Fruchtig und leicht",
              price: { amount: 3.9, currency: "EUR" },
              allergens: ["GLUTEN", "EGG", "MILK"],
              tags: ["vegetarisch"],
              availableIn: ["fruehling", "sommer"],
              options: [],
            },
            {
              id: "kuerbis-latte",
              name: "Kürbis-Latte",
              description: "Mit Gewürzen und Milchschaum",
              price: { amount: 4.2, currency: "EUR" },
              allergens: ["MILK"],
              tags: ["vegetarisch"],
              availableIn: ["herbst"],
              options: [{ label: "Hafermilch", priceDelta: 0.4 }],
            },
          ],
        },
      ],
      notes:
        "Bitte informieren Sie uns über Allergien. Pflanzliche Milchalternativen gegen Aufpreis erhältlich.",
    },
    specials: {
      label: "Tagesangebot",
      weekplan: {
        monday: {
          title: "Banana Bread + Cappuccino",
          description: "Hausgemachtes Bananenbrot mit Cappuccino",
          price: { amount: 5.9, currency: "EUR" },
        },
        tuesday: {
          title: "Zimtschnecke + Filterkaffee",
          description: "Frisch gebackene Zimtschnecke mit Filterkaffee",
          price: { amount: 5.2, currency: "EUR" },
        },
        wednesday: {
          title: "Avocado-Brot + Limonade",
          description: "Sauerteig-Toast mit Avocado & Hauslimonade",
          price: { amount: 8.5, currency: "EUR" },
        },
        thursday: {
          title: "Karottenkuchen + Latte",
          description: "Saftiger Kuchen mit Latte Macchiato",
          price: { amount: 7.2, currency: "EUR" },
        },
        friday: {
          title: "Joghurt-Granola + Espresso",
          description: "Joghurtbecher mit Granola & Espresso",
          price: { amount: 6.4, currency: "EUR" },
        },
        saturday: {
          title: "Frühstücksteller klein + Kaffee",
          description: "Kleiner Teller und Filterkaffee",
          price: { amount: 9.5, currency: "EUR" },
        },
        sunday: {
          title: "Blaubeer-Muffin + Cappuccino",
          description: "Frischer Muffin mit Cappuccino",
          price: { amount: 6.2, currency: "EUR" },
        },
      },
    },
  },
  pages: {
    home: {
      path: "/",
      title: "Café Sonnenblume",
      sections: [
        {
          type: "hero",
          id: "hero",
          anchor: "start",
          props: {
            preheading: "Berlin • Prenzlauer Berg",
            heading: "Café Sonnenblume",
            subheading:
              "Hausgemachte Kuchen, fair gehandelter Kaffee und ein Lächeln – jeden Tag.",
            background: { mode: "color", color: "#FFF7E6" },
            textColor: "#2B2B2B",
            ctas: [
              { label: "Zur Speisekarte", href: "#speisekarte", style: "primary" },
              { label: "Kontakt aufnehmen", href: "#kontakt", style: "secondary" },
            ],
          },
        },
        {
          type: "usp",
          id: "usp",
          props: {
            items: [
              {
                icon: "cup",
                title: "Spezialitätenkaffee",
                text: "Sorgfältig geröstet, frisch gemahlen.",
              },
              {
                icon: "cake",
                title: "Hausgemachte Kuchen",
                text: "Täglich frisch aus unserer Backstube.",
              },
              {
                icon: "leaf",
                title: "Regional & Saisonal",
                text: "Zutaten aus der Region – je nach Saison.",
              },
              {
                icon: "sun",
                title: "Gemütliche Terrasse",
                text: "Sonnenplätze für gute Laune.",
              },
            ],
          },
        },
        {
          type: "specials",
          id: "tagesangebot",
          dataRef: "specials",
          props: {
            heading: "Tagesangebot",
            subheading: "Lecker & fair bepreist – nur heute",
            style: "card",
          },
        },
        {
          type: "menu",
          id: "menu",
          anchor: "speisekarte",
          dataRef: "menu",
          props: {
            heading: "Speisekarte",
            layout: "tabs",
            showAllergens: true,
            showCategoryImages: false,
            note: "Alle Preise in Euro. Änderungen vorbehalten.",
          },
        },
        {
          type: "hours",
          id: "hours",
          anchor: "oeffnungszeiten",
          dataRef: "hours",
          props: { heading: "Öffnungszeiten", showKitchen: true, style: "table" },
        },
        {
          type: "contact",
          id: "contact",
          anchor: "kontakt",
          dataRef: "contact",
          props: {
            heading: "Kontakt",
            showMap: true,
            mapHeight: 320,
            showAddress: true,
            showForm: true,
          },
        },
      ],
    },
  },
  features: {
    announcements: { enabled: false, items: [] },
    cookieConsent: {
      enabled: true,
      mode: "banner",
      text:
        "Wir verwenden nur technisch notwendige Cookies, um diese Website bereitzustellen.",
      acceptLabel: "Verstanden",
      manageLabel: "Einstellungen",
      categories: [
        {
          key: "essential",
          label: "Essentiell",
          required: true,
          enabled: true,
          description: "Für die Grundfunktionen der Website erforderlich.",
        },
      ],
    },
  },
  integrations: {
    map: {
      provider: "osm",
      tileUrl: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
      attribution: "© OpenStreetMap-Mitwirkende",
      defaultZoom: 16,
      marker: { title: "Café Sonnenblume", coordinatesRef: "data.contact.coordinates" },
    },
  },
  schema: {
    localBusiness: {
      "@context": "https://schema.org",
      "@type": "CafeOrCoffeeShop",
      name: "Café Sonnenblume",
      description:
        "Warme, freundliche Nachbarschaftscafé mit hausgemachten Kuchen, Frühstück und Spezialitätenkaffee in Berlin-Prenzlauer Berg.",
      address: {
        "@type": "PostalAddress",
        streetAddress: "Sonnenblumenweg 12",
        postalCode: "10437",
        addressLocality: "Berlin",
        addressRegion: "BE",
        addressCountry: "DE",
      },
      geo: { "@type": "GeoCoordinates", latitude: 52.5412, longitude: 13.4125 },
      telephone: "+49 30 12345678",
      email: "hallo@cafe-sonnenblume.de",
      openingHoursSpecification: [
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Monday",
          opens: "08:00",
          closes: "18:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Tuesday",
          opens: "08:00",
          closes: "18:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Wednesday",
          opens: "08:00",
          closes: "18:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Thursday",
          opens: "08:00",
          closes: "18:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Friday",
          opens: "08:00",
          closes: "18:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Saturday",
          opens: "09:00",
          closes: "16:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Sunday",
          opens: "09:00",
          closes: "16:00",
        },
      ],
      servesCuisine: ["Café", "Frühstück", "Hausgemacht"],
      priceRange: "€",
      sameAs: ["https://instagram.com/cafe.sonnenblume"],
    },
  },
} as const;
