export const siteConfig = {
  project: {
    name: "cafe-sonnenblume",
    industry: "Gastronomie - Café",
    type: "Landingpage",
    locale: "de-DE",
    city: "Berlin",
  },
  site: {
    name: "Café Sonnenblume",
    tagline: "Warm. Freundlich. Hausgemacht.",
    contact: {
      email: "hallo@cafe-sonnenblume.de",
      phone: "+49 30 12345678",
      address: { locality: "Berlin", country: "Deutschland" },
      social: {
        instagram: "https://instagram.com/cafe.sonnenblume.berlin",
        facebook: "https://facebook.com/cafe.sonnenblume.berlin",
      },
    },
  },
  seo: {
    title: "Café Sonnenblume Berlin – Kaffee, Frühstück & hausgemachte Kuchen",
    description:
      "Warme, freundliche Atmosphäre im Café Sonnenblume in Berlin. Frischer Kaffee, Frühstück, vegane Optionen und hausgemachte Kuchen. Öffnungszeiten, Speisekarte und Kontakt.",
    keywords: [
      "Café Berlin",
      "Frühstück",
      "Kaffee",
      "Kuchen",
      "vegan",
      "hausgemacht",
      "Limonade",
    ],
    openGraph: {
      type: "website",
      locale: "de_DE",
      siteName: "Café Sonnenblume",
    },
  },
  theme: {
    colors: {
      primary: "#F2C94C",
      primaryDark: "#D9A800",
      surface: "#FFF7E6",
      surfaceAlt: "#FFF1D1",
      text: "#3D2B1F",
      textMuted: "#6B5B4A",
      accent: "#6BBF59",
      muted: "#B08968",
      border: "#E5D6C6",
    },
    typography: {
      heading: { fontFamily: "Source Serif Pro", weight: 700, lineHeight: 1.2 },
      body: { fontFamily: "Inter", weight: 400, lineHeight: 1.6 },
      button: { fontFamily: "Inter", weight: 600 },
    },
    radius: { sm: 8, md: 12, lg: 20 },
    shadows: {
      card: "0 8px 20px rgba(61,43,31,0.08)",
      elevated: "0 12px 28px rgba(61,43,31,0.12)",
    },
    layout: { containerWidth: 1200, gutter: 24, sectionSpacing: 80 },
    buttons: {
      primary: {
        background: "#F2C94C",
        color: "#3D2B1F",
        hoverBackground: "#D9A800",
        radius: 12,
      },
      secondary: {
        background: "#FFF1D1",
        color: "#3D2B1F",
        hoverBackground: "#FFE2A3",
        radius: 12,
      },
    },
  },
  navigation: [
    { label: "Start", href: "#start", cta: false },
    { label: "Über uns", href: "#ueber-uns", cta: false },
    { label: "Speisekarte", href: "#speisekarte", cta: false },
    { label: "Öffnungszeiten", href: "#oeffnungszeiten", cta: false },
    { label: "Kontakt", href: "#kontakt", cta: true },
  ],
  features: {
    announcementBar: {
      enabled: true,
      text: "Sommer-Special: Hausgemachte Holunderblüten-Limonade – jetzt frisch!",
      link: { label: "Zur Speisekarte", href: "#speisekarte" },
      dismissible: true,
    },
    urlaubPopup: {
      enabled: false,
      title: "Betriebsurlaub",
      message:
        "Wir machen vom 24.12. bis 26.12. eine kurze Pause. Ab dem 27.12. sind wir wieder für Sie da.",
      schedule: [{ from: "2026-12-24", to: "2026-12-26" }],
      showOncePerSession: true,
      showDelayMs: 800,
    },
    cookieConsent: {
      enabled: true,
      mode: "minimal",
      services: { essential: true, analytics: false, marketing: false },
      texts: {
        headline: "Cookies",
        description:
          "Wir verwenden nur technisch notwendige Cookies, um diese Website bereitzustellen.",
      },
      links: { privacy: "/datenschutz", imprint: "/impressum" },
    },
  },
  sections: [
    {
      id: "start",
      type: "hero",
      content: {
        pretitle: "Berlin",
        title: "Willkommen im Café Sonnenblume",
        subtitle:
          "Warme Atmosphäre, duftender Kaffee und hausgemachte Köstlichkeiten.",
        badges: ["Vegetarisch & vegan", "Regional & saisonal", "Hausgemacht"],
        primaryCta: { label: "Speisekarte ansehen", href: "#speisekarte" },
        secondaryCta: { label: "Kontakt", href: "#kontakt" },
      },
      media: { type: "none" },
    },
    {
      id: "ueber-uns",
      type: "text-media",
      content: {
        title: "Über uns",
        text: [
          "Im Café Sonnenblume treffen warmes Ambiente und liebevoll zubereitete Speisen aufeinander. Unser Team begrüßt Sie mit einem Lächeln, aromatischem Kaffee und einer Auswahl an frischen, hausgemachten Kuchen.",
          "Wir setzen auf regionale Zutaten, achten auf Saisonalität und bieten eine große Auswahl an vegetarischen und veganen Optionen. Ob zum gemütlichen Frühstück, für die Pause zwischendurch oder den süßen Nachmittag – bei uns sind Sie richtig.",
        ],
        highlights: [
          "Kaffeespezialitäten aus fair gehandelten Bohnen",
          "Vegane und vegetarische Auswahl",
          "Hausgemachte Kuchen & Gebäck",
          "Kostenloses WLAN & bequeme Sitzplätze",
          "To-go & Mehrwegbecher willkommen",
          "Kartenzahlung möglich",
        ],
      },
      layout: { align: "left", mediaPosition: "right" },
    },
    {
      id: "speisekarte",
      type: "menu",
      content: {
        title: "Speisekarte",
        note: "Alle Preise in EUR. Änderungen vorbehalten.",
        menu: {
          currency: "EUR",
          categories: [
            {
              id: "kaffee-espresso",
              name: "Kaffee & Espresso",
              items: [
                {
                  id: "espresso",
                  name: "Espresso",
                  description: "Kräftig und aromatisch, einfach.",
                  price: 2.2,
                  dietary: [],
                  contains: [],
                },
                {
                  id: "doppio",
                  name: "Doppio",
                  description: "Doppelter Espresso für extra Energie.",
                  price: 3.4,
                  dietary: [],
                  contains: [],
                },
                {
                  id: "americano",
                  name: "Americano",
                  description: "Espresso verlängert mit heißem Wasser.",
                  price: 2.9,
                  dietary: [],
                  contains: [],
                },
                {
                  id: "cappuccino",
                  name: "Cappuccino",
                  description: "Espresso mit cremigem Milchschaum.",
                  price: 3.4,
                  dietary: ["vegetarisch"],
                  contains: ["laktose"],
                },
                {
                  id: "latte-macchiato",
                  name: "Latte Macchiato",
                  description: "Viel Milch, sanfter Espresso.",
                  price: 3.8,
                  dietary: ["vegetarisch"],
                  contains: ["laktose"],
                },
                {
                  id: "flat-white",
                  name: "Flat White",
                  description: "Doppio mit samtiger Milch.",
                  price: 3.9,
                  dietary: ["vegetarisch"],
                  contains: ["laktose"],
                },
              ],
              extrasNote:
                "Milchalternativen (Hafer, Soja, laktosefrei) +0,40 €; Sirup (Vanille, Karamell) +0,30 €",
            },
            {
              id: "tee-getraenke",
              name: "Tee & Getränke",
              items: [
                {
                  id: "kraeutertee",
                  name: "Kräutertee",
                  description: "Ausgewählte Kräutermischung, koffeinfrei.",
                  price: 3.2,
                  dietary: ["vegan"],
                  contains: [],
                },
                {
                  id: "gruener-tee",
                  name: "Grüner Tee",
                  description: "Zart-herb, belebend.",
                  price: 3.2,
                  dietary: ["vegan"],
                  contains: [],
                },
                {
                  id: "chai-latte",
                  name: "Chai Latte",
                  description: "Würziger Schwarztee mit Milch und Gewürzen.",
                  price: 3.8,
                  dietary: ["vegetarisch"],
                  contains: ["laktose"],
                },
                {
                  id: "heisse-schokolade",
                  name: "Heiße Schokolade",
                  description: "Vollmundige Trinkschokolade.",n                  price: 3.9,
                  dietary: ["vegetarisch"],
                  contains: ["laktose"],
                },
                {
                  id: "limonade-hausgemacht",
                  name: "Hausgemachte Limonade",
                  description: "Zitronig-frisch, mit saisonalen Kräutern.",
                  price: 3.8,
                  dietary: ["vegan"],
                  contains: [],
                },
                {
                  id: "orangensaft-frisch",
                  name: "Frischer Orangensaft",
                  description: "Frisch gepresst.",
                  price: 4.2,
                  dietary: ["vegan"],
                  contains: [],
                },
              ],
            },
            {
              id: "fruehstueck",
              name: "Frühstück",
              items: [
                {
                  id: "croissant-butter",
                  name: "Croissant mit Butter & Marmelade",
                  description: "Buttriges Croissant mit hausgemachter Fruchtmarmelade.",
                  price: 3.2,
                  dietary: ["vegetarisch"],
                  contains: ["gluten", "laktose"],
                },
                {
                  id: "joghurt-granola",
                  name: "Joghurt mit Granola & Früchten",
                  description: "Naturjoghurt, knuspriges Granola, saisonales Obst.",
                  price: 5.2,
                  dietary: ["vegetarisch"],
                  contains: ["laktose", "nüsse", "gluten"],
                },
                {
                  id: "avocado-toast",
                  name: "Avocado-Toast auf Sauerteig",
                  description: "Reife Avocado, Zitrone, Chili-Flocken, Kresse.",
                  price: 7.5,
                  dietary: ["vegan"],
                  contains: ["gluten"],
                },
                {
                  id: "ruehrei-bauernbrot",
                  name: "Rührei auf Bauernbrot",
                  description: "Kräuter-Rührei auf ofenfrischem Brot.",
                  price: 6.9,
                  dietary: ["vegetarisch"],
                  contains: ["ei", "gluten"],
                },
                {
                  id: "porridge-apfel",
                  name: "Porridge mit Zimt & Apfel",
                  description: "Wärmender Haferbrei, zimtige Äpfel, Ahornsirup.",
                  price: 5.8,
                  dietary: ["vegan"],
                  contains: ["gluten"],
                },
              ],
            },
            {
              id: "suesses",
              name: "Süßes",
              items: [
                {
                  id: "kaesekuchen",
                  name: "Käsekuchen",
                  description: "Klassisch, cremig – nach Hausrezept.",
                  price: 3.8,
                  dietary: ["vegetarisch"],
                  contains: ["laktose", "gluten", "ei"],
                },
                {
                  id: "brownie",
                  name: "Schokoladen-Brownie",
                  description: "Saftig, schokoladig.",
                  price: 3.2,
                  dietary: [],
                  contains: ["gluten", "ei", "nüsse"],
                },
                {
                  id: "zimtschnecke",
                  name: "Zimtschnecke",
                  description: "Mit Zimt und feiner Glasur.",
                  price: 3,
                  dietary: [],
                  contains: ["gluten", "laktose"],
                },
                {
                  id: "zitronenkuchen-vegan",
                  name: "Veganer Zitronenkuchen",
                  description: "Frisch, zitronig und saftig.",
                  price: 3.6,
                  dietary: ["vegan"],
                  contains: ["gluten"],
                },
              ],
            },
            {
              id: "herzhaft",
              name: "Herzhaft",
              items: [
                {
                  id: "gemuese-quiche",
                  name: "Gemüse-Quiche",
                  description: "Mit saisonalem Gemüse und Kräutern.",
                  price: 6.5,
                  dietary: ["vegetarisch"],
                  contains: ["gluten", "ei", "laktose"],
                },
                {
                  id: "panini-mozzarella",
                  name: "Panini Mozzarella & Tomate",
                  description: "Mit Basilikum-Pesto.",
                  price: 6.9,
                  dietary: ["vegetarisch"],
                  contains: ["gluten", "laktose", "nüsse"],
                },
                {
                  id: "tomatensuppe",
                  name: "Hausgemachte Tomatensuppe",
                  description: "Mit Basilikum und knusprigem Brot.",
                  price: 5.9,
                  dietary: ["vegan"],
                  contains: ["gluten"],
                },
              ],
            },
          ],
        },
      },
    },
    {
      id: "oeffnungszeiten",
      type: "hours",
      content: {
        title: "Öffnungszeiten",
        timezone: "Europe/Berlin",
        regular: {
          monday: [{ open: "08:00", close: "18:00" }],
          tuesday: [{ open: "08:00", close: "18:00" }],
          wednesday: [{ open: "08:00", close: "18:00" }],
          thursday: [{ open: "08:00", close: "18:00" }],
          friday: [{ open: "08:00", close: "18:00" }],
          saturday: [{ open: "09:00", close: "17:00" }],
          sunday: [{ open: "09:00", close: "16:00" }],
        },
        notes: [
          "Küche bis 30 Minuten vor Schließung.",
          "Feiertage können abweichen.",
        ],
      },
    },
    {
      id: "kontakt",
      type: "contact",
      content: {
        title: "Kontakt",
        text:
          "Wir freuen uns auf Ihre Nachricht. Für Reservierungen und Anfragen nutzen Sie bitte das Formular oder rufen Sie uns an.",
        contact: {
          phone: "+49 30 12345678",
          email: "hallo@cafe-sonnenblume.de",
          address: { locality: "Berlin", country: "Deutschland" },
          maps: {
            label: "Auf Google Maps öffnen",
            href: "https://www.google.com/maps?q=Berlin",
          },
        },
        form: {
          id: "kontakt-formular",
          submit: {
            method: "email",
            to: "hallo@cafe-sonnenblume.de",
            subject: "Neue Anfrage über die Website",
          },
          antiSpam: { honeypotName: "website", timeThresholdSeconds: 3 },
          fields: [
            {
              name: "name",
              label: "Name",
              type: "text",
              required: true,
              minLength: 2,
              maxLength: 80,
            },
            { name: "email", label: "E-Mail", type: "email", required: true },
            { name: "telefon", label: "Telefon", type: "tel", required: false },
            {
              name: "anliegen",
              label: "Ihr Anliegen",
              type: "select",
              required: true,
              options: ["Allgemeine Frage", "Reservierung", "Catering/Bestellung"],
            },
            {
              name: "nachricht",
              label: "Nachricht",
              type: "textarea",
              required: true,
              minLength: 10,
              maxLength: 1000,
            },
            {
              name: "einwilligung",
              label:
                "Ich stimme der Verarbeitung meiner Daten gemäß Datenschutz zu.",
              type: "checkbox",
              required: true,
              link: { label: "Datenschutz", href: "/datenschutz" },
            },
          ],
          messages: {
            success: "Vielen Dank! Wir melden uns schnellstmöglich.",
            error: "Leider gab es ein Problem. Bitte versuchen Sie es erneut.",
          },
        },
      },
    },
  ],
  footer: {
    branding: "Café Sonnenblume",
    navigation: [
      { label: "Start", href: "#start" },
      { label: "Über uns", href: "#ueber-uns" },
      { label: "Speisekarte", href: "#speisekarte" },
      { label: "Öffnungszeiten", href: "#oeffnungszeiten" },
      { label: "Kontakt", href: "#kontakt" },
    ],
    legalLinks: { privacy: "/datenschutz", imprint: "/impressum" },
    contact: {
      email: "hallo@cafe-sonnenblume.de",
      phone: "+49 30 12345678",
      address: { locality: "Berlin", country: "Deutschland" },
    },
    hoursSummary: "Mo–Fr 08:00–18:00 · Sa 09:00–17:00 · So 09:00–16:00",
  },
};

export default siteConfig;
