/* Autogenerated site-config for Zahnarztpraxis Timo Krieg */
export default {
  site: {
    name: "Zahnarztpraxis Timo Krieg",
    industry: "Zahnarztpraxis",
    language: "de",
    locale: "de-DE",
  },
  repository: {
    provider: "github",
    owner: "timokrieg84-alt",
    repo: "timo-krieg-site",
    branch: "main",
  },
  branding: {
    logo: {
      src: "/assets/branding/logo.svg",
      alt: "Zahnarztpraxis Timo Krieg Logo",
    },
    colors: {
      primary: "#1E88E5",
      primaryDark: "#1565C0",
      secondary: "#26A69A",
      accent: "#FFC107",
      text: "#1F2937",
      mutedText: "#6B7280",
      background: "#FFFFFF",
      surface: "#F7FAFC",
      border: "#E5E7EB",
    },
    typography: {
      heading: {
        fontFamily: "Playfair Display",
        weights: [400, 600, 700],
      },
      body: {
        fontFamily: "Inter",
        weights: [400, 500, 600],
      },
      mono: {
        fontFamily: "JetBrains Mono",
        weights: [400, 600],
      },
    },
    icons: {
      favicon: "/assets/branding/favicon.ico",
      touchIcon: "/assets/branding/apple-touch-icon.png",
    },
  },
  navigation: {
    main: [
      { label: "Startseite", path: "/", ariaLabel: "Zur Startseite" },
      { label: "Leistungen", path: "/leistungen", ariaLabel: "Zu den Leistungen" },
      { label: "Team", path: "/team", ariaLabel: "Zum Praxisteam" },
      { label: "Kontakt", path: "/kontakt", ariaLabel: "Zur Kontaktseite" },
    ],
    footer: [
      { label: "Startseite", path: "/" },
      { label: "Leistungen", path: "/leistungen" },
      { label: "Team", path: "/team" },
      { label: "Kontakt", path: "/kontakt" },
    ],
    cta: { label: "Termin anfragen", path: "/kontakt#termin", style: "primary" },
  },
  features: {
    holidayPopup: {
      enabled: false,
      id: "holiday-popup",
      title: "Urlaub – eingeschränkte Erreichbarkeit",
      message:
        "Unsere Praxis ist im angegebenen Zeitraum nur eingeschränkt erreichbar. Nutzen Sie bitte das Kontaktformular – wir melden uns schnellstmöglich zurück.",
      schedules: [],
      showOnPages: ["/", "/kontakt"],
      dismissible: true,
    },
    emergencyBanner: {
      enabled: false,
      id: "emergency-banner",
      text: "Akute Zahnschmerzen? Wir halten täglich Notfall-Slots bereit. Bitte nutzen Sie das Kontaktformular.",
      showOnPages: ["/", "/kontakt"],
    },
    cookieConsent: {
      enabled: false,
      mode: "opt-in",
      text: "Wir verwenden nur technisch notwendige Cookies, um diese Website bereitzustellen.",
      buttons: { accept: "Einverstanden", decline: "Ablehnen", details: "Details" },
    },
    analytics: { enabled: false, provider: "" },
  },
  content: {
    services: [
      {
        id: "pzr",
        slug: "professionelle-zahnreinigung",
        title: "Professionelle Zahnreinigung (PZR)",
        summary: "Gründliche Entfernung von Belägen für gesunde Zähne und Zahnfleisch.",
        description:
          "Die Professionelle Zahnreinigung entfernt harte und weiche Beläge auch an schwer zugänglichen Stellen. Anschließend werden die Zähne poliert und fluoridiert. Regelmäßige PZR unterstützt die Vorbeugung von Karies und Parodontitis.",
        benefits: [
          "Reduziert Karies- und Parodontitisrisiko",
          "Sanfte Entfernung von Zahnstein und Verfärbungen",
          "Glatt polierte Oberflächen für weniger Plaqueanlagerung",
        ],
        treatments: [
          "Zahnsteinentfernung",
          "Air-Polishing/Politur",
          "Fluoridierung",
          "Individuelle Mundhygiene-Beratung",
        ],
        notes: "Empfehlung: 1–2× jährlich, individuell nach Risiko.",
      },
      {
        id: "fuellungen",
        slug: "kompositfuellungen",
        title: "Zahnfarbene Kompositfüllungen",
        summary: "Ästhetische und langlebige Versorgung bei kariösen Defekten.",
        description:
          "Moderne Kompositmaterialien ermöglichen substanzschonende, zahnfarbene Füllungen mit hoher Stabilität. Die Farbauswahl erfolgt individuell, sodass sich die Füllung harmonisch einfügt.",
        benefits: [
          "Natürliche Ästhetik",
          "Substanzschonende Präparation",
          "Hohe Haltbarkeit bei korrekter Pflege",
        ],
        treatments: ["Kariesentfernung", "Adhäsivtechnik", "Schichtaufbau", "Feinpolitur"],
        notes: "Abrechnung nach BEMA/GOZ gemäß Indikation.",
      },
      {
        id: "endodontie",
        slug: "wurzelbehandlung",
        title: "Wurzelbehandlung (Endodontie)",
        summary: "Zahnerhalt bei Entzündungen des Zahnnervs.",
        description:
          "Bei einer Reizung oder Entzündung des Zahnnervs kann eine Wurzelbehandlung den Zahn langfristig erhalten. Nach gründlicher Reinigung und Desinfektion der Wurzelkanäle erfolgt die dichte Füllung und der bakteriendichte Verschluss.",
        benefits: [
          "Erhalt des eigenen Zahns",
          "Schmerzlinderung",
          "Langfristige Prognose bei konsequenter Nachsorge",
        ],
        treatments: [
          "Lokalanästhesie",
          "Maschinelle Aufbereitung",
          "Ultraschall-aktivierte Spülung",
          "Thermoplastische Wurzelfüllung",
        ],
        notes: "Individuelle Aufklärung zu Alternativen und Prognose.",
      },
      {
        id: "parodontologie",
        slug: "parodontitis-behandlung",
        title: "Parodontitis-Behandlung",
        summary: "Systematische Therapie entzündlicher Erkrankungen des Zahnhalteapparats.",
        description:
          "Parodontitis führt unbehandelt zu Zahnfleischrückgang und Knochenabbau. Mit einer systematischen Parodontaltherapie werden Beläge unterhalb des Zahnfleischs entfernt, Entzündungen reduziert und der Zahnhalt verbessert.",
        benefits: [
          "Reduktion von Entzündungen und Blutungen",
          "Stabilisierung des Zahnhalteapparats",
          "Individuelle Nachsorge (UPT)",
        ],
        treatments: [
          "Initialtherapie",
          "Subgingivale Instrumentierung",
          "Bakterientests (indikationsbezogen)",
          "Unterstützende Parodontaltherapie (UPT)",
        ],
        notes: "Regelmäßige Nachsorge essenziell für den Langzeiterfolg.",
      },
      {
        id: "zahnersatz",
        slug: "zahnersatz",
        title: "Zahnersatz: Kronen, Brücken, Prothesen",
        summary: "Funktionelle und ästhetische Lösungen bei Zahnsubstanzverlust.",
        description:
          "Je nach Situation kommen festsitzende oder herausnehmbare Versorgungen zum Einsatz. Nach eingehender Diagnostik wird ein individueller Behandlungsplan erstellt – von der Materialauswahl bis zur Eingliederung.",
        benefits: [
          "Wiederherstellung von Funktion und Ästhetik",
          "Individuelle Material- und Farbwahl",
          "Präzise Zusammenarbeit mit Meisterlabor",
        ],
        treatments: [
          "Teil- und Vollkronen",
          "Brücken",
          "Modellguss- und Teleskopprothesen",
          "Okklusionsanpassung und Nachsorge",
        ],
        notes: "Transparente Aufklärung zu Optionen und Kosten.",
      },
      {
        id: "implantologie",
        slug: "implantate",
        title: "Implantate",
        summary: "Festsitzender Ersatz verlorener Zähne auf künstlichen Zahnwurzeln.",
        description:
          "Implantate dienen als stabile Basis für Kronen, Brücken oder Prothesen. Nach Planung und Einheilphase wird die prothetische Versorgung individuell hergestellt und eingegliedert.",
        benefits: ["Hoher Tragekomfort", "Schonung gesunder Nachbarzähne", "Sehr gute Funktion und Ästhetik"],
        treatments: ["3D-Planung (indikationsbezogen)", "Implantatinsertion", "Einheilphase", "Suprakonstruktion"],
        notes:
          "Voraussetzungen wie Knochensituation und Hygiene werden individuell geprüft.",
      },
      {
        id: "aesthetik",
        slug: "aesthetische-zahnheilkunde",
        title: "Ästhetische Zahnheilkunde",
        summary: "Harmonisches Lächeln mit schonenden Verfahren.",
        description:
          "Vom professionellen Bleaching bis zu Veneers – die ästhetische Zahnheilkunde bietet vielfältige Möglichkeiten, Farbe und Form der Zähne zu optimieren.",
        benefits: ["Schonende Verfahren", "Planbare Ergebnisse", "Individuelle Beratung"],
        treatments: ["In-Office- und Home-Bleaching", "Veneers", "Konturkorrekturen", "Kompositaufbauten"],
        notes: "Vorab Befundaufnahme und Aufklärung zu Grenzen/Alternativen.",
      },
      {
        id: "kinder",
        slug: "kinderzahnheilkunde",
        title: "Kinderzahnheilkunde",
        summary: "Einfühlsame Betreuung und Prophylaxe für Kinderzähne.",
        description:
          "Mit kindgerechter Erklärung und sanften Methoden fördern wir eine positive Zahnarzterfahrung. Dazu gehören Früherkennungsuntersuchungen, Fissurenversiegelung und Ernährungsberatung.",
        benefits: ["Kindgerechte Atmosphäre", "Frühzeitige Prävention", "Elternberatung"],
        treatments: ["Fissurenversiegelung", "Fluoridierung", "Kariesbehandlung", "Mundhygiene-Training"],
        notes: "Regelmäßige Kontrollen fördern gesunde Zahn­entwicklung.",
      },
      {
        id: "notfall",
        slug: "notfall",
        title: "Akute Schmerzen & Notfälle",
        summary:
          "Schnelle Hilfe bei akuten Beschwerden – wir halten Notfall-Termine bereit.",
        description:
          "Bei plötzlichen Zahnschmerzen oder abgebrochenen Füllungen bieten wir zeitnahe Hilfe. Bitte schildern Sie Ihr Anliegen im Kontaktformular, damit wir schnell reagieren können.",
        benefits: [
          "Zeitnahe Terminvergabe",
          "Schmerzlindernde Erstversorgung",
          "Transparente weitere Planung",
        ],
        treatments: [
          "Diagnostik und Schmerzbehandlung",
          "Provisorische Versorgung",
          "Weiterführende Therapieplanung",
        ],
        notes:
          "Bei schweren Verletzungen wenden Sie sich bitte an den zahnärztlichen Notdienst Ihrer Region.",
      },
    ],
    team: [
      {
        id: "timo-krieg",
        name: "Dr. med. dent. Timo Krieg",
        role: "Zahnarzt – Praxisinhaber",
        qualifications: [
          "Studium der Zahnmedizin",
          "Fortbildungen in Endodontie und Prothetik",
        ],
        photo: "/assets/team/timo-krieg.jpg",
        bio:
          "Mit Ruhe, Präzision und klarer Kommunikation legt Dr. Timo Krieg Wert auf nachhaltige, zahnerhaltende Behandlungen. Moderne Technik und ein respektvoller Umgang stehen im Mittelpunkt.",
        languages: ["Deutsch", "Englisch"],
        focus: ["Endodontie", "Prothetik", "Allgemeine Zahnheilkunde"],
      },
      {
        id: "anna-weber",
        name: "Dr. med. dent. Anna Weber",
        role: "Zahnärztin",
        qualifications: [
          "Curriculum Parodontologie",
          "Fortbildungen in Ästhetischer Zahnheilkunde",
        ],
        photo: "/assets/team/anna-weber.jpg",
        bio:
          "Dr. Anna Weber kombiniert fundierte Diagnostik mit einfühlsamer Behandlung. Ihr Schwerpunkt liegt auf Parodontologie und Ästhetik mit Blick fürs Detail.",
        languages: ["Deutsch", "Englisch"],
        focus: ["Parodontologie", "Ästhetik", "Füllungstherapie"],
      },
      {
        id: "lisa-schneider",
        name: "Lisa Schneider",
        role: "ZMP – Prophylaxe",
        qualifications: [
          "Zahnmedizinische Prophylaxeassistenz (ZMP)",
          "Fortbildung Air-Polishing",
        ],
        photo: "/assets/team/lisa-schneider.jpg",
        bio:
          "Als Prophylaxe-Expertin motiviert Lisa Schneider zu alltagsnaher Mundhygiene und sorgt für gründliche, angenehme Zahnreinigungen.",
        languages: ["Deutsch"],
        focus: ["Professionelle Zahnreinigung", "Mundhygiene-Coaching"],
      },
    ],
    testimonials: [
      {
        id: "m-bauer",
        name: "M. Bauer",
        text:
          "Sehr freundliches Team, schnelle Terminvergabe und eine gründliche, schmerzfreie Behandlung. Klare Empfehlung!",
        rating: 5,
      },
      {
        id: "s-neumann",
        name: "S. Neumann",
        text:
          "Moderne Praxis und verständliche Aufklärung. Ich habe mich jederzeit gut aufgehoben gefühlt.",
        rating: 5,
      },
      {
        id: "l-koehler",
        name: "L. Köhler",
        text:
          "Top Prophylaxe! Meine Zähne fühlen sich jedes Mal super glatt und sauber an.",
        rating: 5,
      },
    ],
    faqs: [
      {
        id: "terminvergabe",
        question: "Wie schnell erhalte ich einen Termin?",
        answer:
          "In der Regel finden wir kurzfristige Termine. Bei akuten Schmerzen halten wir täglich Notfall-Slots bereit. Nutzen Sie bitte das Kontaktformular zur schnellen Abstimmung.",
        tags: ["Termin", "Notfall"],
      },
      {
        id: "neupatienten",
        question: "Sind Neupatientinnen und -patienten willkommen?",
        answer:
          "Ja. Bringen Sie bitte vorhandene Unterlagen wie Medikamentenliste, Bonusheft und – falls vorhanden – Röntgenbilder mit.",
        tags: ["Neupatient"],
      },
      {
        id: "angst",
        question: "Behandeln Sie Angstpatienten?",
        answer:
          "Ja. Wir nehmen uns Zeit, erklären jeden Schritt verständlich und arbeiten mit besonders schonenden Methoden.",
        tags: ["Angstpatienten"],
      },
      {
        id: "pzr-haeufigkeit",
        question: "Wie oft ist eine PZR empfehlenswert?",
        answer:
          "Meist 1–2 Mal pro Jahr. Bei erhöhtem Risiko (z. B. Parodontitis) können kürzere Intervalle sinnvoll sein.",
        tags: ["PZR", "Prophylaxe"],
      },
      {
        id: "zahlung",
        question: "Welche Zahlungsarten sind möglich?",
        answer:
          "Die Abrechnung erfolgt gemäß BEMA/GOZ. Selbstanteile können üblicherweise per EC-Karte oder Überweisung beglichen werden.",
        tags: ["Zahlung", "Abrechnung"],
      },
      {
        id: "roentgen",
        question: "Wird geröntgt?",
        answer:
          "Nur wenn medizinisch notwendig. Wir setzen auf strahlungsarme, digitale Verfahren und klären vorab auf.",
        tags: ["Diagnostik", "Röntgen"],
      },
      {
        id: "implantate",
        question: "Sind Implantate für mich geeignet?",
        answer:
          "Das hängt von Knochensituation, Allgemeingesundheit und Mundhygiene ab. Wir beraten Sie individuell und stellen Alternativen vor.",
        tags: ["Implantate"],
      },
      {
        id: "garantie-zahnersatz",
        question: "Gibt es eine Garantie auf Zahnersatz?",
        answer:
          "Im Rahmen der gesetzlichen Vorgaben und bei regelmäßiger Nachsorge bieten wir transparente Regelungen. Details klären wir im persönlichen Gespräch.",
        tags: ["Zahnersatz"],
      },
    ],
    forms: {
      contact: {
        id: "contact-form",
        title: "Kontakt & Terminanfrage",
        description:
          "Teilen Sie uns Ihr Anliegen mit. Wir melden uns zeitnah zur Terminabstimmung.",
        action: {
          type: "github-issues",
          repository: { owner: "timokrieg84-alt", repo: "timo-krieg-site" },
          issue: {
            titleTemplate: "Kontaktanfrage von {{vorname}} {{nachname}}",
            labels: ["kontakt", "formular"],
            bodyTemplate:
              "Anliegen: {{anliegen}}\nWunschtermin: {{wunschtermin}}\nTelefon: {{telefon}}\nE-Mail: {{email}}\nNachricht:\n{{nachricht}}\nEinwilligung: {{einwilligung}}",
          },
        },
        fields: [
          { name: "vorname", label: "Vorname", type: "text", required: true, autocomplete: "given-name" },
          { name: "nachname", label: "Nachname", type: "text", required: true, autocomplete: "family-name" },
          {
            name: "email",
            label: "E-Mail",
            type: "email",
            required: true,
            autocomplete: "email",
            validation: { pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$", message: "Bitte geben Sie eine gültige E-Mail-Adresse ein." },
          },
          {
            name: "telefon",
            label: "Telefon (optional)",
            type: "tel",
            required: false,
            autocomplete: "tel",
            validation: { pattern: "^[0-9+()\\-/\\s]{6,}$", message: "Bitte geben Sie eine gültige Telefonnummer ein." },
          },
          {
            name: "anliegen",
            label: "Anliegen",
            type: "select",
            required: true,
            options: [
              "Allgemeine Anfrage",
              "Terminwunsch",
              "Akute Schmerzen",
              "Prophylaxe (PZR)",
              "Zahnersatz",
              "Implantate",
              "Kinderzahnheilkunde",
            ],
          },
          { name: "wunschtermin", label: "Wunschtermin", type: "date", required: false },
          { name: "nachricht", label: "Nachricht", type: "textarea", required: true, placeholder: "" },
          {
            name: "einwilligung",
            label: "Ich willige in die Verarbeitung meiner Angaben zum Zweck der Kontaktaufnahme ein.",
            type: "checkbox",
            required: true,
          },
        ],
        submit: {
          label: "Anfrage senden",
          successMessage: "Vielen Dank! Wir melden uns schnellstmöglich.",
          errorMessage: "Leider ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
        },
        spamProtection: { honeypot: true, timeTrapSeconds: 3 },
      },
    },
    openingHours: [
      { day: "Montag", hours: "08:00–12:00, 14:00–18:00" },
      { day: "Dienstag", hours: "08:00–12:00, 14:00–18:00" },
      { day: "Mittwoch", hours: "08:00–13:00" },
      { day: "Donnerstag", hours: "08:00–12:00, 14:00–19:00" },
      { day: "Freitag", hours: "08:00–13:00" },
      { day: "Samstag", hours: "geschlossen" },
      { day: "Sonntag", hours: "geschlossen" },
    ],
  },
  pages: [
    {
      key: "home",
      title: "Startseite",
      path: "/",
      seo: {
        title: "Zahnarztpraxis Timo Krieg – Moderne Zahnmedizin mit Zeit und Zuwendung",
        description:
          "Ihr Partner für schonende, nachhaltige Zahnbehandlung: Prophylaxe, Füllungen, Wurzelbehandlung, Parodontologie, Zahnersatz, Ästhetik, Kinderzahnheilkunde.",
        robots: "index,follow",
      },
      sections: [
        {
          id: "hero",
          type: "hero",
          headline: "Moderne Zahnmedizin mit Zeit und Zuwendung",
          subheadline:
            "Persönlich, transparent und auf dem neuesten Stand – für Ihr gesundes Lächeln.",
          image: { src: "/assets/hero/hero-praxis.jpg", alt: "Freundliches Zahnarzt-Team in moderner Praxis" },
          primaryCta: { label: "Termin anfragen", href: "/kontakt#termin", style: "primary" },
          secondaryCta: { label: "Leistungen ansehen", href: "/leistungen", style: "secondary" },
          badges: ["Schonende Behandlung", "Kurze Wartezeiten", "Transparente Beratung"],
        },
        {
          id: "usp",
          type: "features-grid",
          title: "Warum zu uns",
          items: [
            { icon: "shield-check", title: "Zahnerhalt im Fokus", text: "Wir wählen immer die schonendste, nachhaltige Therapie." },
            { icon: "sparkles", title: "Ästhetik & Funktion", text: "Schöne Ergebnisse mit zuverlässiger Bissfunktion." },
            { icon: "chip", title: "Moderne Technik", text: "Digitale Diagnostik und präzise Behandlungsmethoden." },
            { icon: "heart", title: "Einfühlsam", text: "Klare Aufklärung und ein ruhiges Behandlungsklima." },
          ],
        },
        {
          id: "services-preview",
          type: "services-grid",
          title: "Unsere Leistungen",
          intro: "Von Prophylaxe bis Zahnersatz – wir beraten Sie individuell.",
          items: ["pzr", "fuellungen", "endodontie", "parodontologie", "zahnersatz", "aesthetik"],
          cta: { label: "Alle Leistungen", href: "/leistungen" },
        },
        {
          id: "team-teaser",
          type: "team-teaser",
          title: "Lernen Sie uns kennen",
          intro: "Wir nehmen uns Zeit für Ihre Fragen und Wünsche.",
          members: ["timo-krieg", "anna-weber", "lisa-schneider"],
          cta: { label: "Zum gesamten Team", href: "/team" },
        },
        {
          id: "testimonials",
          type: "testimonial-slider",
          title: "Stimmen unserer Patientinnen und Patienten",
          items: ["m-bauer", "s-neumann", "l-koehler"],
        },
        {
          id: "faq-preview",
          type: "faq-accordion",
          title: "Häufige Fragen",
          items: ["terminvergabe", "neupatienten", "angst", "pzr-haeufigkeit"],
          cta: { label: "Weitere Fragen", href: "/kontakt#faq" },
        },
        {
          id: "contact-cta",
          type: "cta-banner",
          title: "Sie haben Fragen oder wünschen einen Termin?",
          text: "Schreiben Sie uns – wir melden uns zeitnah.",
          primaryCta: { label: "Kontakt aufnehmen", href: "/kontakt#termin" },
        },
      ],
    },
    {
      key: "leistungen",
      title: "Leistungen",
      path: "/leistungen",
      seo: {
        title: "Leistungen – Zahnarztpraxis Timo Krieg",
        description:
          "Übersicht unserer Leistungen: PZR, Füllungen, Endodontie, Parodontologie, Zahnersatz, Implantate, Ästhetik und Kinderzahnheilkunde.",
        robots: "index,follow",
      },
      sections: [
        { id: "leistungen-hero", type: "page-hero", headline: "Unsere Leistungen", subheadline: "Individuell, transparent und auf Ihre Bedürfnisse abgestimmt." },
        {
          id: "leistungen-list",
          type: "services-list",
          items: [
            "pzr",
            "fuellungen",
            "endodontie",
            "parodontologie",
            "zahnersatz",
            "implantologie",
            "aesthetik",
            "kinder",
            "notfall",
          ],
          detailMode: "accordion",
        },
        {
          id: "leistungen-faq",
          type: "faq-accordion",
          title: "Fragen zu Behandlungen",
          items: ["implantate", "garantie-zahnersatz", "roentgen", "zahlung"],
        },
        {
          id: "leistungen-cta",
          type: "cta-banner",
          title: "Beratung gewünscht?",
          text: "Wir nehmen uns Zeit für Ihre Anliegen und erstellen einen klaren Behandlungsplan.",
          primaryCta: { label: "Beratung anfragen", href: "/kontakt#termin" },
        },
      ],
    },
    {
      key: "team",
      title: "Team",
      path: "/team",
      seo: {
        title: "Team – Zahnarztpraxis Timo Krieg",
        description:
          "Lernen Sie unser Team kennen: Dr. Timo Krieg, Dr. Anna Weber und Lisa Schneider.",
        robots: "index,follow",
      },
      sections: [
        { id: "team-hero", type: "page-hero", headline: "Unser Team", subheadline: "Kompetent, freundlich und respektvoll – für Ihre Zahngesundheit." },
        { id: "team-grid", type: "team-grid", members: ["timo-krieg", "anna-weber", "lisa-schneider"] },
        {
          id: "werte",
          type: "features-grid",
          title: "Unsere Praxiswerte",
          items: [
            { icon: "handshake", title: "Transparenz", text: "Klare Aufklärung und gemeinsam getroffene Entscheidungen." },
            { icon: "leaf", title: "Schonung", text: "So viel wie nötig, so wenig wie möglich." },
            { icon: "clock", title: "Zuverlässigkeit", text: "Pünktliche Termine und strukturierte Abläufe." },
          ],
        },
      ],
    },
    {
      key: "kontakt",
      title: "Kontakt",
      path: "/kontakt",
      seo: {
        title: "Kontakt – Zahnarztpraxis Timo Krieg",
        description:
          "Kontakt und Terminanfrage. Öffnungszeiten und schnelle Hilfe bei akuten Beschwerden.",
        robots: "index,follow",
      },
      sections: [
        { id: "kontakt-hero", type: "page-hero", headline: "Kontakt & Termine", subheadline: "Wir freuen uns auf Ihre Nachricht. Bei akuten Schmerzen vermerken Sie dies bitte im Formular." },
        { id: "termin", type: "form", title: "Terminanfrage", formRef: "contact-form" },
        { id: "zeiten", type: "opening-hours", title: "Öffnungszeiten", itemsRef: "openingHours", note: "Individuelle Terminabsprachen möglich." },
        { id: "kontakt-faq", type: "faq-accordion", title: "Häufige Fragen", items: ["terminvergabe", "neupatienten", "zahlung"] },
      ],
    },
  ],
} as const;
